export async function loadSnapmakerTemplate() {
  const candidates = ["../tenis%20keychain%20v2.gcode", "../Cube.gcode"];
  for (const url of candidates) {
    try {
      const response = await fetch(url, { cache: "no-store" });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const text = await response.text();
      if (!text.includes("; HEADER_BLOCK_START") || !text.includes("; CONFIG_BLOCK_START")) {
        throw new Error(`${url} missing Snapmaker container blocks`);
      }
      return text;
    } catch (error) {
      console.warn(`Could not load ${url}; trying next template.`, error);
    }
  }
  return null;
}

export function createSnapmakerGcode({
  generatedLayerCount,
  layerZ,
  retractZHopMm,
  toolDeretractSpeed,
  toolProfile,
  toolRetractLength,
  toolRetractSpeed,
  toolTemp,
}) {
  function wrapWithSnapmakerTemplate(template, executableBlock, c) {
    const startMarker = "; EXECUTABLE_BLOCK_START";
    const endMarker = "; EXECUTABLE_BLOCK_END";
    const start = template.indexOf(startMarker);
    const endMarkerStart = template.indexOf(endMarker, start);
    if (start < 0 || endMarkerStart < 0) return executableBlock;
    const endLine = template.indexOf("\n", endMarkerStart);
    const end = endLine < 0 ? template.length : endLine + 1;
    let withExecutable = `${template.slice(0, start)}${executableBlock.trimEnd()}\n\n${template.slice(end)}`;
    withExecutable = updateSnapmakerFilamentSummary(withExecutable, executableBlock, c);
    const configStartMarker = "; CONFIG_BLOCK_START";
    const configEndMarker = "; CONFIG_BLOCK_END";
    const configStart = withExecutable.indexOf(configStartMarker);
    const configEndMarkerStart = withExecutable.indexOf(configEndMarker, configStart);
    if (configStart < 0 || configEndMarkerStart < 0) return withExecutable;
    const configEndLine = withExecutable.indexOf("\n", configEndMarkerStart);
    const configEnd = configEndLine < 0 ? withExecutable.length : configEndLine + 1;
    return `${withExecutable.slice(0, configStart)}${snapmakerConfigBlock(c, template)}\n${withExecutable.slice(configEnd)}`;
  }

  function updateSnapmakerFilamentSummary(gcode, executableBlock, c) {
    const stats = filamentStatsFromExecutable(executableBlock, c);
    const mm = stats.mm.map((value) => value.toFixed(2)).join(", ");
    const cm3 = stats.cm3.map((value) => value.toFixed(2)).join(", ");
    const grams = stats.grams.map((value) => value.toFixed(2)).join(", ");
    const totalGrams = stats.grams.reduce((sum, value) => sum + value, 0);
    return gcode
      .replace(/^; filament used \[mm\] = .*$/m, `; filament used [mm] = ${mm}`)
      .replace(/^; filament used \[cm3\] = .*$/m, `; filament used [cm3] = ${cm3}`)
      .replace(/^; filament used \[g\] = .*$/m, `; filament used [g] = ${grams}`)
      .replace(/^; filament cost = .*$/m, `; filament cost = ${stats.grams.map(() => "0.00").join(", ")}`)
      .replace(/^; total filament used \[g\] = .*$/m, `; total filament used [g] = ${totalGrams.toFixed(2)}`)
      .replace(/^; total filament cost = .*$/m, "; total filament cost = 0.00")
      .replace(/^; total layers count = .*$/m, `; total layers count = ${generatedLayerCount(c)}`);
  }

  function filamentStatsFromExecutable(executableBlock, c) {
    const mm = [0, 0, 0, 0];
    let activeTool = null;
    for (const rawLine of executableBlock.split(/\r?\n/)) {
      const line = rawLine.split(";")[0].trim();
      const toolMatch = line.match(/^T([0-3])\b/);
      if (toolMatch) {
        activeTool = Number(toolMatch[1]);
        continue;
      }
      if (activeTool === null || !line.startsWith("G1")) continue;
      const eMatch = line.match(/(?:^|\s)E(-?\d+(?:\.\d+)?)/);
      if (!eMatch) continue;
      const e = Number(eMatch[1]);
      if (e > 0) mm[activeTool] += e;
    }
    const filamentArea = Math.PI * (1.75 / 2) ** 2;
    const densities = [0, 1, 2, 3].map((tool) => Number(toolProfile(tool, c).density ?? (toolProfile(tool, c).type === "PLA" ? 1.25 : 1.24)));
    const cm3 = mm.map((length) => (length * filamentArea) / 1000);
    const grams = cm3.map((volume, index) => volume * densities[index]);
    return { mm, cm3, grams };
  }

  function wrapSnapmakerOrcaGcode(c, executableBlock) {
    return [
      snapmakerHeaderBlock(c),
      snapmakerThumbnailPlaceholders(),
      executableBlock.trimEnd(),
      snapmakerConfigBlock(c),
      "",
    ].join("\n\n");
  }

  function snapmakerHeaderBlock(c) {
    const maxZ = layerZ(c, generatedLayerCount(c));
    const now = new Date();
    const stamp = now.toISOString().slice(0, 19).replace("T", " ");
    return [
      "; HEADER_BLOCK_START",
      `; generated by PunchPrint UI using Snapmaker Orca compatible container on ${stamp}`,
      `; total layer number: ${generatedLayerCount(c)}`,
      "; filament_density: 1.24,1.24,1.24,1.25",
      "; filament_diameter: 1.75,1.75,1.75,1.75",
      `; max_z_height: ${maxZ.toFixed(2)}`,
      "; HEADER_BLOCK_END",
    ].join("\n");
  }

  function snapmakerThumbnailPlaceholders() {
    return [
      "; THUMBNAIL_BLOCK_START",
      "; THUMBNAIL_BLOCK_END",
      "",
      "; THUMBNAIL_BLOCK_START",
      "; THUMBNAIL_BLOCK_END",
    ].join("\n");
  }

  function snapmakerConfigBlock(c, template = null) {
    const overrides = snapmakerConfigOverrides(c);
    const templateBlock = template ? extractConfigBlock(template) : null;
    if (templateBlock) return mergeSnapmakerConfigBlock(templateBlock, overrides);
    return minimalSnapmakerConfigBlock(c, overrides);
  }

  function snapmakerConfigOverrides(c) {
    const nozzleTemps = [0, 1, 2, 3].map((tool) => toolTemp(tool, c)).join(",");
    const firstLayerTemps = [0, 1, 2, 3].map((tool) => toolTemp(tool, c, true)).join(",");
    const filamentTypes = [0, 1, 2, 3].map((tool) => toolProfile(tool, c).type).join(";");
    const filamentColors = [0, 1, 2, 3].map((tool) => toolProfile(tool, c).color).join(";");
    const retractLengths = [0, 1, 2, 3].map((tool) => toolRetractLength(tool, c));
    const retractSpeeds = [0, 1, 2, 3].map((tool) => toolRetractSpeed(tool, c));
    const deretractSpeeds = [0, 1, 2, 3].map((tool) => toolDeretractSpeed(tool, c));
    return new Map([
      ["generated_by", "PunchPrint UI"],
      ["printer_model", "Snapmaker U1"],
      ["layer_height", String(c.layerHeight)],
      ["first_layer_height", c.firstLayerHeight.toFixed(3)],
      ["nozzle_diameter", `${c.nozzleDiameter},${c.nozzleDiameter},${c.nozzleDiameter},${c.nozzleDiameter}`],
      ["line_width", String(c.beadWidth)],
      ["filament_diameter", "1.75,1.75,1.75,1.75"],
      ["filament_density", [0, 1, 2, 3].map((tool) => toolProfile(tool, c).density ?? 1.24).join(",")],
      ["filament_flow_ratio", `${c.extrusionFlow},1,1,1`],
      ["first_layer_bed_temperature", String(Math.round(c.bedTemp))],
      ["bed_temperature", `${Math.round(c.bedTemp)},${Math.round(c.bedTemp)},${Math.round(c.bedTemp)},${Math.round(c.bedTemp)}`],
      ["first_layer_temperature", firstLayerTemps],
      ["nozzle_temperature", nozzleTemps],
      ["filament_type", filamentTypes],
      ["filament_colour", filamentColors],
      ["filament_retraction_length", `${retractLengths[0]},${retractLengths[1]},${retractLengths[2]},nil`],
      ["filament_retraction_speed", `${retractSpeeds[0]},${retractSpeeds[1]},${retractSpeeds[2]},nil`],
      ["filament_deretraction_speed", `${deretractSpeeds[0]},${deretractSpeeds[1]},${deretractSpeeds[2]},nil`],
      ["retraction_length", retractLengths.join(",")],
      ["retraction_speed", retractSpeeds.join(",")],
      ["z_hop", `${retractZHopMm},${retractZHopMm},${retractZHopMm},${retractZHopMm}`],
      ["bed_shape", `0.5x1,${(c.bedWidth + 0.5).toFixed(1)}x1,${(c.bedWidth + 0.5).toFixed(1)}x${(c.bedDepth + 1).toFixed(1)},0.5x${(c.bedDepth + 1).toFixed(1)}`],
    ]);
  }

  return {
    extractConfigBlock,
    filamentStatsFromExecutable,
    mergeSnapmakerConfigBlock,
    minimalSnapmakerConfigBlock,
    snapmakerConfigBlock,
    snapmakerConfigOverrides,
    snapmakerHeaderBlock,
    snapmakerThumbnailPlaceholders,
    updateSnapmakerFilamentSummary,
    wrapSnapmakerOrcaGcode,
    wrapWithSnapmakerTemplate,
  };
}

function extractConfigBlock(text) {
  const startMarker = "; CONFIG_BLOCK_START";
  const endMarker = "; CONFIG_BLOCK_END";
  const start = text.indexOf(startMarker);
  const end = text.indexOf(endMarker, start);
  if (start < 0 || end < 0) return null;
  const endLine = text.indexOf("\n", end);
  return text.slice(start, endLine < 0 ? text.length : endLine).trimEnd();
}

function mergeSnapmakerConfigBlock(templateBlock, overrides) {
  const seen = new Set();
  const lines = templateBlock.split(/\r?\n/).map((line) => {
    const match = line.match(/^; ([^=]+?) = (.*)$/);
    if (!match) return line;
    const key = match[1].trim();
    if (!overrides.has(key)) return line;
    seen.add(key);
    return `; ${key} = ${overrides.get(key)}`;
  });
  const endIndex = lines.findIndex((line) => line.trim() === "; CONFIG_BLOCK_END");
  const insertIndex = endIndex >= 0 ? endIndex : lines.length;
  const additions = [...overrides.entries()]
    .filter(([key]) => !seen.has(key))
    .map(([key, value]) => `; ${key} = ${value}`);
  lines.splice(insertIndex, 0, ...additions);
  return lines.join("\n");
}

function minimalSnapmakerConfigBlock(c, overrides) {
  return [
    "; CONFIG_BLOCK_START",
    "; generated by PunchPrint UI",
    `; printer_model = ${overrides.get("printer_model")}`,
    `; layer_height = ${overrides.get("layer_height")}`,
    `; first_layer_height = ${overrides.get("first_layer_height")}`,
    `; nozzle_diameter = ${overrides.get("nozzle_diameter")}`,
    `; line_width = ${overrides.get("line_width")}`,
    "; initial_layer_line_width = 0.5",
    "; outer_wall_line_width = 0.42",
    "; inner_wall_line_width = 0.45",
    "; internal_solid_infill_line_width = 0.42",
    "; sparse_infill_line_width = 0.45",
    "; top_surface_line_width = 0.42",
    "; support_line_width = 0.42",
    `; filament_diameter = ${overrides.get("filament_diameter")}`,
    `; filament_flow_ratio = ${overrides.get("filament_flow_ratio")}`,
    "; filament_max_volumetric_speed = 2.4,4,21,13",
    "; pressure_advance = 0.4,0.4,0.02,0.02",
    "; close_fan_the_first_x_layers = 1,1,1,3",
    "; fan_max_speed = 100,100,100,40",
    "; fan_min_speed = 100,100,100,10",
    "; full_fan_speed_layer = 0,0,0,0",
    `; first_layer_bed_temperature = ${overrides.get("first_layer_bed_temperature")}`,
    `; bed_temperature = ${overrides.get("bed_temperature")}`,
    `; first_layer_temperature = ${overrides.get("first_layer_temperature")}`,
    `; nozzle_temperature = ${overrides.get("nozzle_temperature")}`,
    "; nozzle_temperature_range_high = 250,210,210,270",
    "; nozzle_temperature_range_low = 200,190,190,230",
    `; filament_type = ${overrides.get("filament_type")}`,
    `; filament_colour = ${overrides.get("filament_colour")}`,
    `; filament_retraction_length = ${overrides.get("filament_retraction_length")}`,
    `; filament_retraction_speed = ${overrides.get("filament_retraction_speed")}`,
    `; filament_deretraction_speed = ${overrides.get("filament_deretraction_speed")}`,
    `; retraction_length = ${overrides.get("retraction_length")}`,
    `; retraction_speed = ${overrides.get("retraction_speed")}`,
    "; outer_wall_speed = 200",
    "; inner_wall_speed = 300",
    "; sparse_infill_speed = 270",
    "; travel_speed = 500",
    "; enable_prime_tower = 1",
    "; prime_tower_width = 35",
    "; prime_tower_brim_width = 5",
    "; prime_tower_brim_chamfer = 1",
    "; prime_tower_brim_chamfer_max_width = 4",
    "; prime_volume = 45",
    "; purge_in_prime_tower = 0",
    "; use_relative_e_distances = 1",
    "; thumbnails = 48x48/PNG, 300x300/PNG",
    "; thumbnails_format = PNG",
    `; bed_shape = ${overrides.get("bed_shape")}`,
    "; CONFIG_BLOCK_END",
  ].join("\n");
}
