export const CONTROL_IDS = [
  "workflowMode",
  "bedWidth",
  "bedDepth",
  "nozzleDiameter",
  "beadWidth",
  "layerHeight",
  "firstLayerHeight",
  "baseLayerCount",
  "extrusionFlow",
  "epi",
  "gridLineCount",
  "tpuFillMode",
  "pcbPinContactsEnabled",
  "pcbPinContactEpi",
  "pcbPinContactWidth",
  "materialOverlapWidth",
  "previewLayer",
  "drawMode",
  "frameLoops",
  "frameSpacing",
  "shapeMaterial",
  "regionSelectMode",
  "materialBoundaryFrames",
  "tpuSnakeEnabled",
  "printMode",
  "exposedSnakeMode",
  "bottomLayerCount",
  "tpuSnakeLayerCount",
  "t0BlockLayerCount",
  "tpuSnakeRemainderMaterial",
  "tpuSnakeMaterialOrder",
  "tpuSnakeCornerRelief",
  "tpuSnakeAllowCrossings",
  "tpuSnakeTargetLength",
  "tpuSnakeNormalLeadLength",
  "tool",
  "extruderTemp",
  "bedTemp",
];

export const PRINT_CONSTANTS = {
  RETRACT_Z_HOP_MM: 0.4,
  RESTART_RAMP_MM: 3.0,
  TPU_PRIME_RAMP_MM: 60.0,
  TPU_BODY_PRIME_RAMP_MM: 8.0,
  TPU_SERPENTINE_PRIME_RAMP_MM: 6.0,
  TPU_SERPENTINE_PREPRIME_MM: 0.55,
  TPU_TOWER_SERPENTINE_PRIME_RAMP_MM: 14.0,
  TPU_TOWER_SERPENTINE_PREPRIME_MM: 0.2,
  TPU_SINGLE_LAYER_SERPENTINE_FLOW: 1.12,
  TPU_SINGLE_LAYER_SERPENTINE_PREPRIME_MM: 0.65,
  TPU_SINGLE_LAYER_SERPENTINE_PRIME_RAMP_MM: 9.0,
  TPU_GRID_PRIME_RAMP_MM: 4.0,
  TPU_GRID_PREPRIME_MM: 0.45,
  SNAP_GUIDE_SCREEN_PX: 8,
  PLA_REFERENCE_FIRST_LAYER_WIDTH: 0.5,
  PLA_REFERENCE_BOTTOM_WIDTH: 0.501589,
  PLA_REFERENCE_BOTTOM_PITCH: 0.6330,
  PLA_REFERENCE_FIRST_LAYER_E_PER_MM: 0.04656,
  PLA_REFERENCE_WALL_FEED: 2151,
  PLA_REFERENCE_BOTTOM_FEED: 2143,
  WIPE_TOWER_PRIME_SPREAD_MM: 180.0,
  NUMERIC_DRAW_DELAY_MS: 320,
  SNAKE_TARGET_DRAW_DELAY_MS: 900,
};
