export function buildGcodeHeaderLines({
  c,
  state,
  materials,
  totalLayers,
  snakeHeaderStats,
  firstLayerMaterial,
  toolProfile,
  toolTemp,
  toolPrintSpeed,
  t0BlockFirstLayer,
  t0BlockTopLayer,
  tpuSnakeFirstLayer,
  tpuSnakeTopLayer,
  layerSpanCount,
  tpuSnakeEffectiveWidth,
  frameGridOverlapWidth,
  snakeTargetSummary,
  constants,
}) {
  const {
    PLA_REFERENCE_BOTTOM_WIDTH,
    PLA_REFERENCE_BOTTOM_PITCH,
    PLA_REFERENCE_FIRST_LAYER_E_PER_MM,
    TPU_GRID_PREPRIME_MM,
    TPU_GRID_PRIME_RAMP_MM,
    TPU_SERPENTINE_PREPRIME_MM,
    TPU_SERPENTINE_PRIME_RAMP_MM,
    TPU_TOWER_SERPENTINE_PREPRIME_MM,
    TPU_TOWER_SERPENTINE_PRIME_RAMP_MM,
    TPU_SINGLE_LAYER_SERPENTINE_FLOW,
    TPU_SINGLE_LAYER_SERPENTINE_PREPRIME_MM,
    TPU_SINGLE_LAYER_SERPENTINE_PRIME_RAMP_MM,
  } = constants;

  return [
    "; PunchPrint UI generated Snapmaker-Orca compatible G-code",
    "; Generator version: auto-workflow-conductive-pin-frame-v1-20260827",
    `; Print mode: ${c.printMode} (${printModeLabel(c)})`,
    `; Shape material map: ${JSON.stringify(state.shapes.map((shape) => ({ id: shape.id, type: shape.type, tool: shape.material ?? c.tool })))}`,
    `; Active tools: ${materials.map((material) => `T${material}`).join(", ")}`,
    `; Tool profiles: ${materials.map((material) => `T${material}=${toolProfile(material, c).label}@${toolTemp(material, c)}C/${toolPrintSpeed(material, c)}mm-s`).join(", ")}`,
    `; T0 Black TPU temperature source: UI nozzle temperature ${toolTemp(0, c)}C; T1/T2/T3 use fixed material profiles.`,
    "; NOTE: UI G-code splits grid paths by material; layer-alternating boundary overlap interlocks only the grid lines perpendicular to material boundaries.",
    "; NOTE: Toolchange commands include an auto-placed wipe tower that avoids the object bounding box.",
    `; NOTE: Automatic PLA outer frames are disabled; outer frame loops, when enabled, use T${firstLayerMaterial} ${toolProfile(firstLayerMaterial, c).label} on the whole printable union outline.`,
    "; NOTE: Frame paths use the outer union boundary; overlapping internal edit boundaries are not printed.",
    "; NOTE: Raw SVG material boundary frames are not exported in grid mode; printable internal boundaries are derived from snapped grid segments to avoid double-image paths.",
    "; NOTE: G-code Y coordinates are flipped from the UI canvas coordinate system so slicer preview matches the on-screen drawing orientation.",
    "; NOTE: Material grids are generated from snapped complete EPI cells for every material; outside/void cells are non-printing cutouts.",
    "; NOTE: Cell-grid generation stores material occupancy first; printable grid paths are then rebuilt from that mask as long same-material scanline segments.",
    "; NOTE: Before G-code writing, every material bucket is normalized into the longest same-line segments possible after all geometry postprocess steps.",
    "; NOTE: White TPU outer frame is derived from the whole printable union, not from white-only material boundaries.",
    "; NOTE: Base layer count is the total generated layer count; bottom support layers delay the first serpentine layer.",
    "; NOTE: Each generated base layer uses one nominal Z height; crossing lines are strengthened by flow multiplier, not by extra Z lift.",
    c.exposedSnakeMode
      ? `; NOTE: Exposed serpentine mode: layer 1 is solid T${firstLayerMaterial} ${toolProfile(firstLayerMaterial, c).label}; upper layers print only snapped-cell T0 black TPU grid/solid paths and serpentine paths.`
      : c.printMode === "wrapped"
        ? `; NOTE: Wrapped serpentine mode: layer 1 is forced to T${firstLayerMaterial} ${toolProfile(firstLayerMaterial, c).label}; T0 blocks print from layer ${t0BlockFirstLayer(c)} to ${t0BlockTopLayer(c)}; serpentine prints from layer ${tpuSnakeFirstLayer(c)} to ${tpuSnakeTopLayer(c)}; non-T0 same-line overlaps avoid T0 paths, while orthogonal crossings are controlled by the crossing toggle.`
        : `; NOTE: Layer 1 grid is forced to T${firstLayerMaterial} ${toolProfile(firstLayerMaterial, c).label}; grid line generation always includes both min/max boundary lines, not extra frame paths.`,
    c.exposedSnakeMode
      ? `; NOTE: Exposed white TPU first layer follows the Object_1_TPU_8m44s path style with T${firstLayerMaterial} material: 0.25mm first layer, inner/outer wall, diagonal bottom surface, ${PLA_REFERENCE_BOTTOM_WIDTH.toFixed(6)} mm bottom width, ${PLA_REFERENCE_BOTTOM_PITCH.toFixed(4)} mm pitch, ${PLA_REFERENCE_FIRST_LAYER_E_PER_MM.toFixed(5)} measured E/mm.`
      : "; NOTE: Exposed Object_1-style first-layer mode is off.",
    "; NOTE: TPU target-length paths use scanline-style row/corridor candidates inspired by 3DP single-wire trace filling.",
    "; NOTE: Red open SVG strokes are imported as guided T0 serpentine paths; guide vertices are snapped to the printable EPI grid and emitted as orthogonal path geometry.",
    "; NOTE: When two TPU endpoints are selected, the T0 path is limited to a local corridor around the endpoint TPU regions and subtracts itself from other materials.",
    `; NOTE: On layers with T0 serpentine paths, material order is ${c.tpuSnakeMaterialOrder === "t0-first" ? "T0 black TPU first, then remainder/non-T0 grid materials" : "remainder/non-T0 grid materials first, then T0 black TPU"}.`,
    `; Nozzle diameter mm: ${c.nozzleDiameter.toFixed(3)}`,
    `; Bead width mm: ${c.beadWidth.toFixed(3)}`,
    `; Layer height mm: ${c.layerHeight.toFixed(3)}`,
    `; First layer height mm: ${c.firstLayerHeight.toFixed(3)}`,
    `; Base layer count: ${c.baseLayerCount}`,
    `; PCB pin extra raised layers: ${c.pcbPinExtraLayerCount}`,
    `; Bottom support layers: ${c.bottomLayerCount}`,
    `; T0 block layers target: ${c.t0BlockLayerCount}`,
    `; Generated layer count: ${totalLayers}`,
    `; Derived base thickness mm: ${c.baseThickness.toFixed(3)}`,
    `; Black TPU T0 flow ratio: ${c.extrusionFlow.toFixed(3)}; other tools: 1.000`,
    `; Material print speeds mm/s: ${materials.map((material) => `T${material}=${toolPrintSpeed(material, c)}`).join(", ")}`,
    `; EPI: ${c.epi}`,
    `; Pitch mm: ${c.pitch.toFixed(5)}`,
    `; Grid line count: ${c.gridLineCount}`,
    `; Grid line width mm: ${c.gridLineWidth.toFixed(5)}`,
    `; PCB pin contact grid: ${c.pcbPinContactsEnabled ? `on, EPI ${c.pcbPinContactEpi}, width ${c.pcbPinContactWidth.toFixed(3)} mm, extra raised layers ${c.pcbPinExtraLayerCount}` : "off"}`,
    "; NOTE: PCB cutouts are treated as void masks; XIAO pin pads are ring-shaped with center holes. D2/D7/GND pads use T0 conductive TPU; other pin pads use T2 white TPU.",
    `; T0 serpentine effective width mm: ${tpuSnakeEffectiveWidth(c).toFixed(3)}`,
    `; T0 serpentine print strands: ${c.gridLineCount} x ${c.beadWidth.toFixed(3)}mm from one centerline`,
    `; T0 black TPU fill mode default: ${c.tpuFillMode}`,
    "; NOTE: Selected T0 shapes can override fill mode with S=solid and G=grid.",
    "; NOTE: T0 solid fill converts the same rasterized black EPI cells into merged concentric fill paths; original SVG contours are not used as solid paths.",
    "; NOTE: T0 solid/grid state is classified on the same snapped cell map used for T0 occupancy, so solid blocks do not leave hollow residual cells from a separate classifier.",
    "; NOTE: Exposed-mode T0 grid and T0 solid fill use the same global material bounds as the raster phase origin, so their snapped cell outlines share the same coordinates.",
    "; NOTE: T0 grid line spans and non-T0 material grid spans inside selected solid black cells are subtracted before concentric cell fill is emitted.",
    "; NOTE: T0 grid regions are rasterized to complete EPI cells before G-code generation; original SVG contours are only design input.",
    "; NOTE: Rectangular T0 shapes are generated only from their best contiguous EPI cell block by 1D overlap IoU; generic majority sampling is skipped for those rectangles.",
    "; NOTE: Non-rectangular T0 shapes use majority coverage, so narrow imported features snap to the grid cells they cover most.",
    "; NOTE: Exposed-mode T0 block geometry is also generated from the snapped complete-cell mask; raw SVG T0 boundary paths are not emitted.",
    "; NOTE: Final T0 grid spans, solid cell paths, and serpentine paths are treated as the authoritative black TPU mask; non-T0 same-layer paths are clipped after T0 is finalized.",
    "; NOTE: T0 retracts do not wipe backwards over the just-printed body line; restart prime is distributed along T0 line moves.",
    `; NOTE: T0 grid restart uses ${TPU_GRID_PREPRIME_MM.toFixed(2)} mm pre-prime, then spreads the remaining prime over the first ${TPU_GRID_PRIME_RAMP_MM.toFixed(1)} mm of the grid line.`,
    `; NOTE: T0 serpentine restart uses ${TPU_SERPENTINE_PREPRIME_MM.toFixed(2)} mm pre-prime, then spreads the remaining prime over the first ${TPU_SERPENTINE_PRIME_RAMP_MM.toFixed(1)} mm of the path.`,
    `; NOTE: The first T0 serpentine after wipe tower uses smoother restart: ${TPU_TOWER_SERPENTINE_PREPRIME_MM.toFixed(2)} mm pre-prime and ${TPU_TOWER_SERPENTINE_PRIME_RAMP_MM.toFixed(1)} mm ramp to reduce start blobs.`,
    "; NOTE: T0 layers with serpentine paths print nearby block/grid geometry before each serpentine path to reduce long tower-to-serpentine restarts.",
    `; NOTE: Single-layer T0 serpentine uses reinforced flow ${TPU_SINGLE_LAYER_SERPENTINE_FLOW.toFixed(2)}, ${TPU_SINGLE_LAYER_SERPENTINE_PREPRIME_MM.toFixed(2)} mm pre-prime, and ${TPU_SINGLE_LAYER_SERPENTINE_PRIME_RAMP_MM.toFixed(1)} mm restart ramp.`,
    "; NOTE: T0 serpentine endpoints are extended inward into the selected TPU blocks so endpoint retracts happen inside the block.",
    "; NOTE: T0 serpentine endpoint leads are emitted as orthogonal segments only; diagonal endpoint-to-grid joins are not used.",
    "; NOTE: T0 serpentine endpoint lead distance is rounded up to a whole grid pitch so lead anchors remain on grid intersections.",
    "; NOTE: T0 serpentine body paths must stay at least two grid pitches away from black TPU grid points; endpoint normal lead transition zones are exempt.",
    c.exposedSnakeMode
      ? "; NOTE: In exposed serpentine mode, T0 serpentine path planning reuses the embedded-mode T0 boundary/grid constraints so paths remain stable when switching modes."
      : "; NOTE: In embedded serpentine mode, T0 serpentine paths avoid the black TPU grid except endpoint lead segments.",
    c.exposedSnakeMode
      ? "; NOTE: In exposed serpentine mode, T0 grid vertical lines use the same flow as horizontal lines to reduce first-TPU-layer bulging."
      : "; NOTE: Embedded grid vertical crossings keep a 1.2x local flow multiplier for stronger intersections.",
    "; NOTE: T0 body travels use a short-distance pressure-keeping rule; longer body travels use a 1.0 mm retract, with faster body-to-body restart priming for later serpentine paths.",
    `; White TPU outer frame loops: ${c.frameLoops}, spacing mm: ${c.frameSpacing.toFixed(3)}`,
    `; Grid-to-frame overlap mm: ${frameGridOverlapWidth(c).toFixed(3)} (automatic PLA frame disabled)`,
    `; Material boundary overlap mm: ${c.materialOverlapWidth.toFixed(3)}`,
    `; Material boundary frames: ${c.materialBoundaryFrames ? "on" : "off"}`,
    `; T0 TPU serpentine: ${c.tpuSnakeEnabled ? `on, layers ${tpuSnakeFirstLayer(c)}-${tpuSnakeTopLayer(c)} (${layerSpanCount(tpuSnakeFirstLayer(c), tpuSnakeTopLayer(c))} actual layers), T0 blocks ${t0BlockFirstLayer(c)}-${t0BlockTopLayer(c)} (${layerSpanCount(t0BlockFirstLayer(c), t0BlockTopLayer(c))} actual layers), remainder T${c.tpuSnakeRemainderMaterial}, order ${c.tpuSnakeMaterialOrder}, corner relief ${c.tpuSnakeCornerRelief ? "on" : "off"}, orthogonal crossings ${c.tpuSnakeAllowCrossings ? "kept" : "cut"}, targets ${snakeTargetSummary(c)}, normal lead ${c.tpuSnakeNormalLeadLength.toFixed(1)} mm` : "off"}`,
    `; T0 TPU serpentine generated paths on preview/export layer: ${snakeHeaderStats ? snakeHeaderStats.count : 0}${state.tpuSnake.conflict ? `; last conflict: ${state.tpuSnake.conflict}` : ""}`,
    `; Opening mm: ${c.opening.toFixed(5)}`,
  ];
}

export function printModeLabel(c) {
  if (c.printMode === "exposed") return "裸露";
  if (c.printMode === "wrapped") return "包裹";
  return "交叉";
}
