export function createInitialAppState(controls) {
  return {
    defaultTpuFillMode: controls.tpuFillMode?.value ?? "grid",
    shapeMode: "empty",
    frame: { x: 0, y: 0, w: 0, h: 0 },
    path: [],
    shapes: [],
    polylineClosed: false,
    activeVertexIndex: -1,
    selectedShapeIndex: -1,
    selectedShapeIndices: new Set(),
    selectedRegionKey: null,
    selectedRegionPoint: null,
    regionMaterialOverrides: new Map(),
    activeShapeHandle: null,
    activeShapeMove: null,
    pendingShape: null,
    draftShape: null,
    snapGuides: [],
    dragging: false,
    dragStart: null,
    undoSavedForDrag: false,
    scrollLock: null,
    tpuSnake: {
      endpoints: [],
      connections: [],
      picking: false,
      editingConnectionIndex: -1,
      selectedConnectionIndex: -1,
      conflict: null,
    },
    clipboard: {
      shapes: [],
      regionMaterialOverrides: [],
      pasteCount: 0,
    },
    undoStack: [],
    gridRasterCache: new Map(),
    materialGridCache: new Map(),
  };
}
