export function buildMachineStartLines({
  c,
  materials,
  firstTool,
  toolTemp,
  toolProfile,
  toolFanSpeed,
  toolAuxFanSpeed,
  g1,
  totalLayers,
}) {
  return [
    "; EXECUTABLE_BLOCK_START",
    "M73 P0 R1",
    "M106 S0",
    "M106 P2 S0",
    ";TYPE:Custom",
    ";===== date: 20260625 =====================",
    "PRINT_START",
    "DEFECT_DETECTION_START",
    `SET_PRINT_STATS_INFO TOTAL_LAYER=${totalLayers} CURRENT_LAYER=0`,
    "TIMELAPSE_START",
    `M140 S${Math.round(c.bedTemp)}`,
    "M104 T0 S140",
    "M204 S10000",
    "G28 X Y",
    "DEFECT_DETECT_NOODLE_FIRST",
    `T${firstTool}`,
    "G90",
    "DEFECT_DETECTION_DETECT_BED",
    "SM_PRINT_CHECK_SWITCH_EXTRUDER",
    "SM_PRINT_EXTRUDER_PREHEAT EXTRUDER=1 TEMP=140",
    "SM_PRINT_AUTO_FEED EXTRUDER=0",
    "SM_PRINT_FLOW_CALIBRATE EXTRUDER=0",
    "SM_PRINT_EXTRUDER_PREHEAT EXTRUDER=2 TEMP=140",
    "SM_PRINT_AUTO_FEED EXTRUDER=1",
    "SM_PRINT_FLOW_CALIBRATE EXTRUDER=1",
    "SM_PRINT_EXTRUDER_PREHEAT EXTRUDER=3 TEMP=140",
    "SM_PRINT_AUTO_FEED EXTRUDER=2",
    "SM_PRINT_FLOW_CALIBRATE EXTRUDER=2",
    "SM_PRINT_AUTO_FEED EXTRUDER=3",
    "SM_PRINT_FLOW_CALIBRATE EXTRUDER=3",
    "M104 S0 T0 A0",
    "M104 S0 T1 A0",
    "M104 S0 T2 A0",
    "M104 S0 T3 A0",
    `M104 T${firstTool} S160`,
    `T${firstTool}`,
    "M106 S255",
    "M106 P2 S0",
    "MOVE_TO_DISCARD_FILAMENT_POSITION",
    `M109 T${firstTool} S160`,
    "ROUGHLY_CLEAN_NOZZLE_WITH_DISCARD",
    "MOVE_TO_XY_IDLE_POSITION_EXTRUDER",
    "G28 Z I140 J140",
    "DETECT_BED_PLATE",
    "G90",
    "G0 Z5 F10000",
    "MOVE_TO_DISCARD_FILAMENT_POSITION",
    "M109 S200",
    "ROUGHLY_CLEAN_NOZZLE",
    "MOVE_TO_XY_IDLE_POSITION_EXTRUDER",
    "FINELY_CLEAN_NOZZLE_STAGE_1",
    "M104 S160",
    "G0 Z5 F10000",
    "MOVE_TO_DISCARD_FILAMENT_POSITION",
    "ROUGHLY_CLEAN_NOZZLE",
    "MOVE_TO_XY_IDLE_POSITION_EXTRUDER",
    "FINELY_CLEAN_NOZZLE_STAGE_2",
    "M106 S255",
    "M109 S160",
    `M190 S${Math.round(c.bedTemp)}`,
    "M107 P2",
    "G90",
    "G0 Z5 F10000",
    "G28 Z",
    "BED_MESH_CALIBRATE PROBE_COUNT=11,11",
    "G90",
    "G1 Z1.5",
    "G0 X85 Y1 Z2 F18000",
    `M109 T${firstTool} S${toolTemp(firstTool, c, true)} ; first tool ${toolProfile(firstTool, c).label}`,
    "G1 Z0.2",
    "M83",
    "G1 X185 E15 F360",
    "G1 Z1.5",
    "G90",
    "G21",
    "M83 ; use relative distances for extrusion",
    `T${firstTool}`,
    ...materials.map((material) => `M104 S${toolTemp(material, c, true)} T${material} ; set ${toolProfile(material, c).label} temperature`),
    `M106 S${toolFanSpeed(firstTool, c)}`,
    `M106 P2 S${toolAuxFanSpeed(firstTool, c)}`,
    g1({ z: 5, f: 30000 }),
  ];
}
